#!/bin/bash

# Populate the database
export PYTHONPATH=$OPENSHIFT_REPO_DIR
export DJANGO_SETTINGS_MODULE=moxious.settings
#python "$OPENSHIFT_REPO_DIR"files/hashcat.py "$OPENSHIFT_REPO_DIR"/test

# Statement to dump contents of database to a file
# mysqldump --password=$OPENSHIFT_MYSQL_DB_PASSWORD -h $OPENSHIFT_MYSQL_DB_HOST -P $OPENSHIFT_MYSQL_DB_PORT -u $OPENSHIFT_MYSQL_DB_USERNAME $OPENSHIFT_GEAR_NAME 
echo mysql --password=$OPENSHIFT_MYSQL_DB_PASSWORD \
      -h $OPENSHIFT_MYSQL_DB_HOST \
      -P $OPENSHIFT_MYSQL_DB_PORT \
      -u $OPENSHIFT_MYSQL_DB_USERNAME \
      $OPENSHIFT_GEAR_NAME

export PYTHONPATH=$OPENSHIFT_REPO_DIR
export DJANGO_SETTINGS_MODULE=moxious.settings

